export default {
  disable: false,
  title: 'PROJECT',
  list: [
    {
      title: 'STR Rule 운영 프로세스 표준화',
      startDate: 'YYYY.MM',
      endDate: 'YYYY.MM',
      description: 'STR Rule 운영을 "검증 가능한 룰"로 전환하기 위한 프로세스 표준화 프로젝트',
      skillKeywords: ['SQL', 'Rule Management', 'Process Standardization', 'STR'],
      achievements: [
        'STR Rule(100+개) 전수 점검을 통해 룰 산출 로직을 SQL로 검증',
        '중복 검출 룰을 식별해 룰셋을 재정비(통합/우선순위/예외조건 정리)',
        '룰 관리 기준(정의/검증/릴리즈/모니터링) 관점의 표준화를 병행하여 STR 운영의 일관성과 효율 강화',
        '룰 결과 검증 쿼리 작성 및 정합성 점검 체크리스트 작성',
        '운영 가이드/매뉴얼 작성 및 표준화 작업',
      ],
    },
    {
      title: '국외 AML 모니터링 체계 도입',
      startDate: 'YYYY.MM',
      endDate: 'YYYY.MM',
      description: '해외 규제 기반 국외 AML 모니터링 체계 도입 프로젝트',
      skillKeywords: ['Elasticsearch', 'Container', 'ETL', 'SQL', 'Monitoring'],
      achievements: [
        '컨테이너 기반 서버 구조 설계 및 구축',
        'Elasticsearch 기반 실시간 대규모 모니터링 시스템 개발',
        '기존 행내 시스템과의 갭(운영/데이터/권한/로그/성능) 해결',
        'ETL 개발 및 운영',
        '오픈 일정 내 안정적 도입 지원',
      ],
    },
    {
      title: 'STR 운영 고도화',
      startDate: 'YYYY.MM',
      endDate: 'YYYY.MM',
      description: 'STR 운영 프로세스 개선 및 효율화 작업',
      skillKeywords: ['SQL', 'Query Optimization', 'STR'],
      achievements: [
        '업무 화면 개발 참여 및 자체 로직 개선을 통한 운영 효율성 향상',
        '대용량 쿼리 튜닝을 통한 쿼리 수행시간 개선',
        '배치 흐름도/테이블 연계도 작성 후 팀 공유 및 공용 매뉴얼 반영',
        '보고 리드타임 단축 및 오탐/재작업률 개선',
      ],
    },
    {
      title: '전산 협업 및 요구사항 정의',
      startDate: 'YYYY.MM',
      endDate: 'YYYY.MM',
      description: 'STR 운영 프로세스 표준화/단순화 관점으로 전산 요건 정의',
      skillKeywords: ['Requirements Analysis', 'UAT', 'Process Improvement'],
      achievements: [
        'STR 운영 프로세스 표준화/단순화 관점으로 전산 요건 정의',
        '요구사항 정의서 작성 및 테스트 시나리오(UAT) 작성',
        '릴리즈 체크리스트 작성 및 이슈 트래킹',
        '유관부서(개발/운영/컴플라이언스/현업) 협업을 통한 일정/품질/리스크 관리',
      ],
    },
  ],
}
